// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID       string `json:"ID"`
	Email    string `json:"Email"`
	Password string `json:"Password"`
	Name     string `json:"Name"`
}
